/**
	Code generated by Gemini (AI Collaborator).
	This module implements an Event Dispatcher for the Pub/Sub pattern in Go.
	It allows multiple subscribers to receive a copy of every event sent,
	overcoming the standard point-to-point limitation of Go channels.
**/

package events

import (
	"domainwatcher/internal/domain/events"
	"sync"
)

// EventDispatcher manages the list of subscribers and event distribution.
type EventDispatcher struct {
	subscribers []chan events.Event
	mu          sync.RWMutex
}

// NewEventDispatcher creates a new instance of the event bus.
func NewEventDispatcher() *EventDispatcher {
	return &EventDispatcher{
		subscribers: make([]chan events.Event, 0),
	}
}

// Subscribe registers a new subscriber and returns a private channel for them.
func (ed *EventDispatcher) Subscribe() chan events.Event {
	ed.mu.Lock()
	defer ed.mu.Unlock()

	// Using a buffered channel to prevent immediate blocking
	ch := make(chan events.Event, 10)
	ed.subscribers = append(ed.subscribers, ch)
	return ch
}

// Publish sends the event to all registered subscribers asynchronously.
func (ed *EventDispatcher) Publish(event events.Event) {
	ed.mu.RLock()
	defer ed.mu.RUnlock()

	for _, ch := range ed.subscribers {
		// Executed in a goroutine to ensure a slow subscriber
		// does not block the Dispatcher's main flow.
		go func(c chan events.Event) {
			c <- event
		}(ch)
	}
}
